import test from 'node:test';
import assert from 'node:assert/strict';
import { handleContactRequest } from '../api/_lib/contact-handler.js';

const now = 10_000;
const validSubmission = { name: 'Åsa O\'Neil', email: 'test+contact@example.com', phone: '+46 70 000 00 00', message: 'We need help reviewing our security environment.', website: '', turnstileToken: 'turnstile-token', submissionId: '123e4567-e89b-42d3-a456-426614174000', formStartedAt: 8_000 };
const config = { enabled: true, resendApiKey: 'resend-secret', fromEmail: 'Website <website@example.com>', toEmail: 'contact@juit.se', turnstileSecretKey: 'turnstile-secret', allowedTurnstileHostnames: ['juitnetsec.se'], upstashUrl: 'https://redis.example', upstashToken: 'redis-secret', rateLimitHashSecret: '12345678901234567890123456789012', rateLimitMax: 5, rateLimitEmailMax: 2, rateLimitWindowSeconds: 900 };
function request(payload = validSubmission, options = {}) { return new Request(options.url || 'https://juitnetsec.se/api/contact', { method: 'POST', headers: { 'content-type': options.contentType || 'application/json', origin: options.origin === undefined ? 'https://juitnetsec.se' : options.origin, 'x-vercel-forwarded-for': '203.0.113.10' }, body: options.rawBody === undefined ? JSON.stringify(payload) : options.rawBody }); }
function dependencies(overrides = {}) { return { now, loadConfig: () => config, consumeRateLimit: async () => ({ allowed: true, remaining: 4, retryAfter: 900 }), verifyCaptcha: async () => true, deliverEmail: async () => ({ id: 'email-id' }), logger: { info() {}, warn() {}, error() {} }, ...overrides }; }

test('accepts a valid four-field contact submission', async () => { let delivered; const response = await handleContactRequest(request(), dependencies({ deliverEmail: async (input) => { delivered = input; return { id: 'email-id' }; } })); assert.equal(response.status, 202); assert.equal(delivered.submission.email, validSubmission.email); assert.equal(delivered.submission.company, undefined); });
test('rejects malformed and whitespace email addresses', async () => { for (const email of ['invalid', 'a@', 'a..b@example.com', 'a@domain', 'a @example.com']) { const response = await handleContactRequest(request({ ...validSubmission, email }), dependencies()); assert.equal(response.status, 400); } });
test('rejects old form fields and missing bot token', async () => { const oldField = await handleContactRequest(request({ ...validSubmission, company: 'Example' }), dependencies()); const bot = await handleContactRequest(request({ ...validSubmission, turnstileToken: '' }), dependencies()); assert.equal(oldField.status, 400); assert.equal(bot.status, 400); });
test('rejects short message, impossible phone, and automated timing', async () => { for (const payload of [{ ...validSubmission, message: 'Short' }, { ...validSubmission, phone: 'not a number' }, { ...validSubmission, formStartedAt: 9_500 }]) { const response = await handleContactRequest(request(payload), dependencies()); assert.equal(response.status, 400); } });
test('returns fake success for a honeypot submission', async () => { let delivered = false; const response = await handleContactRequest(request({ ...validSubmission, website: 'spam.example' }), dependencies({ deliverEmail: async () => { delivered = true; } })); assert.equal(response.status, 202); assert.equal(delivered, false); });
test('rejects GET-like and non-JSON requests', async () => { const noOrigin = new Request('https://juitnetsec.se/api/contact', { method: 'GET' }); const wrongType = request(validSubmission, { contentType: 'text/plain' }); assert.equal((await handleContactRequest(noOrigin, dependencies())).status, 405); assert.equal((await handleContactRequest(wrongType, dependencies())).status, 415); });
test('returns generic failure on provider and rate-limit failures', async () => { const provider = await handleContactRequest(request(), dependencies({ deliverEmail: async () => { throw new Error('private detail'); } })); const limited = await handleContactRequest(request(), dependencies({ consumeRateLimit: async () => ({ allowed: false, remaining: 0, retryAfter: 60 }) })); assert.equal(provider.status, 502); assert.equal((await provider.json()).message.includes('private detail'), false); assert.equal(limited.status, 429); });
